package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// GeneratedQuiz represents a quiz generated by AI for a student
type GeneratedQuiz struct {
	ID            uuid.UUID       `json:"id" db:"id"`
	UserID        uuid.UUID       `json:"user_id" db:"user_id"`
	CourseID      uuid.UUID       `json:"course_id" db:"course_id"`
	Title         string          `json:"title" db:"title"`
	QuizData      json.RawMessage `json:"quiz_data" db:"quiz_data"`
	SourceUnitIDs []uuid.UUID     `json:"source_unit_ids" db:"source_unit_ids"`
	CreatedAt     time.Time       `json:"created_at" db:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at" db:"updated_at"`
}

// GeneratedFlashcardSet represents a flashcard set generated by AI for a student
type GeneratedFlashcardSet struct {
	ID             uuid.UUID       `json:"id" db:"id"`
	UserID         uuid.UUID       `json:"user_id" db:"user_id"`
	CourseID       uuid.UUID       `json:"course_id" db:"course_id"`
	Title          string          `json:"title" db:"title"`
	FlashcardsData json.RawMessage `json:"flashcards_data" db:"flashcards_data"`
	SourceUnitIDs  []uuid.UUID     `json:"source_unit_ids" db:"source_unit_ids"`
	CreatedAt      time.Time       `json:"created_at" db:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at" db:"updated_at"`
}
